export { default as Hero } from "./Hero";
export { default as Process } from "./Process";
export { default as Testimonials } from "./Testimonials";
export { default as Pricing } from "./Pricing";
export { default as FAQ } from "./FAQ";
export { default as CTA } from "./CTA";
export { default as Benefits } from "./Benefits";
export { default as Problem } from "./Problem";
export { default as Solution } from "./Solution";
